AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  cognito-test-userpool-ensure-user

  Sample SAM Template for cognito-test-userpool-ensure-user
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  CognitoTestEnsureUserApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Dev

  EnsureUserFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: ensure-user/
      Handler: app.lambdaHandler
      Runtime: nodejs14.x
      Architectures:
        - x86_64
      Policies:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - cognito-idp:AdminGetUser
              - cognito-idp:AdminCreateUser
              - cognito-idp:AdminSetUserPassword
            Resource: '*'
      Environment:
        Variables:
          COGNITO_USER_POOL_ID: 'us-east-2_32QZBjg1x'
          USER_SERVICE_ENDPOINT: 'https://1rl7kpj033.execute-api.us-east-2.amazonaws.com/Dev'
      Events:
        EnsureUser:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            RestApiId: !Ref CognitoTestEnsureUserApi
            Path: /ensure-user/{userId}
            Method: get

# Outputs:
#   # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
#   # Find out more about other implicit resources you can reference within SAM
#   # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
#   EnsureUserApi:
#     Description: "API Gateway endpoint URL for Prod stage for EnsureUser function"
#     Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/ensure-user/"
#   EnsureUserFunction:
#     Description: "Ensure User Lambda Function ARN"
#     Value: !GetAtt EnsureUserFunction.Arn
#   EnsureUserFunctionIamRole:
#     Description: "Implicit IAM Role created for EnsureUser function"
#     Value: !GetAtt EnsureUserFunctionRole.Arn
