AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  cognito-test-custom-pool-define-auth-trigger-app

  Sample SAM Template for cognito-test-custom-pool-define-auth-trigger-app
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  CognitoTestCustomPoolDefineTriggerFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: app/
      Handler: app.lambdaHandler
      Runtime: nodejs14.x
      Architectures:
        - x86_64

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  CognitoTestCustomPoolDefineTriggerFunction:
    Description: "CognitoTestCustomPoolDefineTriggerFunction Lambda Function ARN"
    Value: !GetAtt CognitoTestCustomPoolDefineTriggerFunction.Arn
  CognitoTestCustomPoolDefineTriggerFunctionIamRole:
    Description: "Implicit IAM Role created for CognitoTestCustomPoolDefineTriggerFunction"
    Value: !GetAtt CognitoTestCustomPoolDefineTriggerFunctionRole.Arn
